name: docker-example-nginx
description: Example Nginx Proxy
repo: github.com/spesnova/docker-example-nginx
image: quay.io/spesnova/docker-example-nginx
command:
ports:
volumes:
  - /etc/nginx/switch:/etc/nginx/switch:ro
net: host
environment:
  - SERVER_NAME=hello.com
