name: docker-example-rails-blue
description: Example Rails App (blue)
repo: github.com/spesnova/docker-example-rails
image: quay.io/spesnova/docker-example-rails
command:
ports:
  - 8091:3000
volumes:
net:
environment:
  - DATABASE_HOST=172.17.8.101
  - DATABASE_PORT=5432
  - DATABASE_USER=hello
  - DATABASE_PASSWORD=world
  - SECRET_KEY_BASE=450a851180c712e6a7ba6f4ab4a9624caddfc02d842eef3315cc47f9b0a16ef3cb5e5b68184d998604076a05d32d108b465f7bfe23623222690be720c7bfd39c
  - RACK_ENV=production
  - RAILS_SERVE_STATIC_FILES=true
  - COLOR=blue
