#!/bin/bash
#
# Usage:
#   script/run bash
#   script/run cap -T
#

set -e

docker run \
  --rm \
  -it \
  --name capistrano.`date +%s` \
  -v /home/core/share/capistrano:/capistrano \
  quay.io/spesnova/docker-example-capistrano \
  $@
