# Load DSL and Setup Up Stages
require 'capistrano/setup'

# Includes default deployment tasks
require "capistrano/console"

# Loads custom tasks from `lib/capistrano/tasks' if you have any defined.
Dir.glob('lib/capistrano/tasks/*.rb').each { |r| import r }

#
# Load default stage
#
invoke :default
